volumes:
  hpp_poject:
  postgres_data:

networks:
  front-tier:
  back-tier:

services:
  web:
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    build: ./web-service-mlflow
    image: web_service
    container_name: web_service
    depends_on:
      - tracking
    ports:
      - "9696:9696"
    networks:
      - front-tier
      - back-tier
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - back-tier

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - back-tier
      - front-tier

  tracking:
    restart: always
    build: ./mlflow
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account-file.json
    volumes:
      - ./web-service-mlflow/silicon-data-423218-q0-179a2dbeb763.json:/app/service-account-file.json
    image: mlflow_server
    container_name: mlflow_server
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - front-tier
      - back-tier
    command: mlflow server --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB} --default-artifact-root gs://mlflow-models-marko --host 0.0.0.0        
