name: CI-Tests
on:
  pull_request:
    branches:
      - 'develop'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        working-directory: "web-service-mlflow"
        run: pip install -r requirements.txt && pip install -r dev-requirements.txt

      - name: Run Unit tests
        working-directory: "web-service-mlflow"
        run: pytest tests/

      - name: Lint
        working-directory: "web-service-mlflow"
        run: pylint --recursive=y .

      - name: Integration Test
        working-directory: 'web-service-mlflow/integraton-test'
        run: |
          . run.sh

  tf-plan:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - name: Terraform Init
      run: |
        cd terraform
        terraform init
    - name: Terraform Plan
      run: |
        cd terraform
        terraform plan
